"""empty message

Revision ID: 7e43fde241c5
Revises: 8176ad4c6ea7
Create Date: 2016-04-15 21:27:06.199943

"""

# revision identifiers, used by Alembic.
revision = '7e43fde241c5'
down_revision = '8176ad4c6ea7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('location', sa.Column('longtiude', sa.Numeric(precision=10, scale=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'longtiude')
    op.drop_column('location', 'latitude')
    ### end Alembic commands ###
