"""empty message

Revision ID: 871167fc0d6b
Revises: b20b3662f9b4
Create Date: 2016-04-25 21:22:14.073683

"""

# revision identifiers, used by Alembic.
revision = '871167fc0d6b'
down_revision = 'b20b3662f9b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('longitude', sa.Numeric(precision=12, scale=8), nullable=True))
    op.drop_column('location', 'longtiude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('longtiude', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=True))
    op.drop_column('location', 'longitude')
    ### end Alembic commands ###
