"""empty message

Revision ID: e84f0e62b351
Revises: None
Create Date: 2016-04-12 23:39:57.601719

"""

# revision identifiers, used by Alembic.
revision = 'e84f0e62b351'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'diagnosis', 'provider', ['provider_id'], ['provider_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnosis', type_='foreignkey')
    ### end Alembic commands ###
